#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/bms?characterEncoding=utf8&useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 996633qq
#    type: com.alibaba.druid.pool.DruidDataSource
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
spring:

  profiles:

    active: ice